bundle:
  name: 'app'
  assets:
    - 'index.js'

template:
  replacements:
    APP_NAME: ${APP_NAME}
    APP_DESCRIPTION: ${APP_DESCRIPTION}
    PUBLIC_URL: ${APP_PUBLIC_URL}

features:
  - minify
  - gzip
  - runtimeChunk
